// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package workflow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "kubeIT/pkg/grpc/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WorkflowManagementServiceClient is the client API for WorkflowManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowManagementServiceClient interface {
	CreateWorkflow(ctx context.Context, in *Workflow, opts ...grpc.CallOption) (*common.StatusReport, error)
	GetWorkflow(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.StatusReport, error)
	DeleteWorkflow(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.StatusReport, error)
	UpdateStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*common.StatusReport, error)
	GetStatus(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*WorkflowStatus, error)
}

type workflowManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowManagementServiceClient(cc grpc.ClientConnInterface) WorkflowManagementServiceClient {
	return &workflowManagementServiceClient{cc}
}

func (c *workflowManagementServiceClient) CreateWorkflow(ctx context.Context, in *Workflow, opts ...grpc.CallOption) (*common.StatusReport, error) {
	out := new(common.StatusReport)
	err := c.cc.Invoke(ctx, "/v1alpha2.workflow.WorkflowManagementService/CreateWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagementServiceClient) GetWorkflow(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.StatusReport, error) {
	out := new(common.StatusReport)
	err := c.cc.Invoke(ctx, "/v1alpha2.workflow.WorkflowManagementService/GetWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagementServiceClient) DeleteWorkflow(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*common.StatusReport, error) {
	out := new(common.StatusReport)
	err := c.cc.Invoke(ctx, "/v1alpha2.workflow.WorkflowManagementService/DeleteWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagementServiceClient) UpdateStatus(ctx context.Context, in *StatusUpdate, opts ...grpc.CallOption) (*common.StatusReport, error) {
	out := new(common.StatusReport)
	err := c.cc.Invoke(ctx, "/v1alpha2.workflow.WorkflowManagementService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowManagementServiceClient) GetStatus(ctx context.Context, in *common.IDRequest, opts ...grpc.CallOption) (*WorkflowStatus, error) {
	out := new(WorkflowStatus)
	err := c.cc.Invoke(ctx, "/v1alpha2.workflow.WorkflowManagementService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowManagementServiceServer is the server API for WorkflowManagementService service.
// All implementations must embed UnimplementedWorkflowManagementServiceServer
// for forward compatibility
type WorkflowManagementServiceServer interface {
	CreateWorkflow(context.Context, *Workflow) (*common.StatusReport, error)
	GetWorkflow(context.Context, *common.IDRequest) (*common.StatusReport, error)
	DeleteWorkflow(context.Context, *common.IDRequest) (*common.StatusReport, error)
	UpdateStatus(context.Context, *StatusUpdate) (*common.StatusReport, error)
	GetStatus(context.Context, *common.IDRequest) (*WorkflowStatus, error)
	mustEmbedUnimplementedWorkflowManagementServiceServer()
}

// UnimplementedWorkflowManagementServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkflowManagementServiceServer struct {
}

func (UnimplementedWorkflowManagementServiceServer) CreateWorkflow(context.Context, *Workflow) (*common.StatusReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedWorkflowManagementServiceServer) GetWorkflow(context.Context, *common.IDRequest) (*common.StatusReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedWorkflowManagementServiceServer) DeleteWorkflow(context.Context, *common.IDRequest) (*common.StatusReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedWorkflowManagementServiceServer) UpdateStatus(context.Context, *StatusUpdate) (*common.StatusReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedWorkflowManagementServiceServer) GetStatus(context.Context, *common.IDRequest) (*WorkflowStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedWorkflowManagementServiceServer) mustEmbedUnimplementedWorkflowManagementServiceServer() {
}

// UnsafeWorkflowManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowManagementServiceServer will
// result in compilation errors.
type UnsafeWorkflowManagementServiceServer interface {
	mustEmbedUnimplementedWorkflowManagementServiceServer()
}

func RegisterWorkflowManagementServiceServer(s grpc.ServiceRegistrar, srv WorkflowManagementServiceServer) {
	s.RegisterService(&WorkflowManagementService_ServiceDesc, srv)
}

func _WorkflowManagementService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Workflow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagementServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.workflow.WorkflowManagementService/CreateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagementServiceServer).CreateWorkflow(ctx, req.(*Workflow))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManagementService_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagementServiceServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.workflow.WorkflowManagementService/GetWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagementServiceServer).GetWorkflow(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManagementService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagementServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.workflow.WorkflowManagementService/DeleteWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagementServiceServer).DeleteWorkflow(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManagementService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagementServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.workflow.WorkflowManagementService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagementServiceServer).UpdateStatus(ctx, req.(*StatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowManagementService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.IDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowManagementServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.workflow.WorkflowManagementService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowManagementServiceServer).GetStatus(ctx, req.(*common.IDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowManagementService_ServiceDesc is the grpc.ServiceDesc for WorkflowManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha2.workflow.WorkflowManagementService",
	HandlerType: (*WorkflowManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowManagementService_CreateWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _WorkflowManagementService_GetWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowManagementService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _WorkflowManagementService_UpdateStatus_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _WorkflowManagementService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/workflow/workflow.proto",
}
