apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: kubeit
data:
  config: |
    artifactRepository:
      s3:
        bucket: kubeit
        keyPrefix: results
        endpoint: YOUR-S3-ENDPOINT
        accessKeySecret:
          name: s3secret
          key: AWS_ACCESS_KEY_ID
        secretKeySecret:
          name: s3secret
          key: AWS_SECRET_ACCESS_KEY
        useSDKCreds: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeit-settings
  namespace: kubeit
data:
  BASEBUCKET: biokube
  NAMESPACE: kubeit
  S3IP: YOUR-S3-ENDPOINT
  S3REGION: RegionOne