// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: pkg/grpc/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrpPermissionLevel int32

const (
	GrpPermissionLevel_GUEST    GrpPermissionLevel = 0
	GrpPermissionLevel_USER     GrpPermissionLevel = 1
	GrpPermissionLevel_CREATOR  GrpPermissionLevel = 2
	GrpPermissionLevel_GRPADMIN GrpPermissionLevel = 3
)

// Enum value maps for GrpPermissionLevel.
var (
	GrpPermissionLevel_name = map[int32]string{
		0: "GUEST",
		1: "USER",
		2: "CREATOR",
		3: "GRPADMIN",
	}
	GrpPermissionLevel_value = map[string]int32{
		"GUEST":    0,
		"USER":     1,
		"CREATOR":  2,
		"GRPADMIN": 3,
	}
)

func (x GrpPermissionLevel) Enum() *GrpPermissionLevel {
	p := new(GrpPermissionLevel)
	*p = x
	return p
}

func (x GrpPermissionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GrpPermissionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_common_common_proto_enumTypes[0].Descriptor()
}

func (GrpPermissionLevel) Type() protoreflect.EnumType {
	return &file_pkg_grpc_common_common_proto_enumTypes[0]
}

func (x GrpPermissionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GrpPermissionLevel.Descriptor instead.
func (GrpPermissionLevel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_common_common_proto_rawDescGZIP(), []int{0}
}

type SharingStatus int32

const (
	SharingStatus_PRIVATE SharingStatus = 0
	SharingStatus_GROUP   SharingStatus = 1
	SharingStatus_ALL     SharingStatus = 2
)

// Enum value maps for SharingStatus.
var (
	SharingStatus_name = map[int32]string{
		0: "PRIVATE",
		1: "GROUP",
		2: "ALL",
	}
	SharingStatus_value = map[string]int32{
		"PRIVATE": 0,
		"GROUP":   1,
		"ALL":     2,
	}
)

func (x SharingStatus) Enum() *SharingStatus {
	p := new(SharingStatus)
	*p = x
	return p
}

func (x SharingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SharingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_grpc_common_common_proto_enumTypes[1].Descriptor()
}

func (SharingStatus) Type() protoreflect.EnumType {
	return &file_pkg_grpc_common_common_proto_enumTypes[1]
}

func (x SharingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SharingStatus.Descriptor instead.
func (SharingStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_grpc_common_common_proto_rawDescGZIP(), []int{1}
}

type StatusReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *StatusReport) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *StatusReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_common_common_proto_rawDescGZIP(), []int{1}
}

var File_pkg_grpc_common_common_proto protoreflect.FileDescriptor

var file_pkg_grpc_common_common_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x32, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22,
	0x40, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x44, 0x0a, 0x12, 0x47, 0x72,
	0x70, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x09, 0x0a, 0x05, 0x47, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x4f, 0x52,
	0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x52, 0x50, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x03,
	0x2a, 0x30, 0x0a, 0x0d, 0x53, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c,
	0x10, 0x02, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x4b, 0x75, 0x62, 0x65, 0x49, 0x54, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x4b, 0x75,
	0x62, 0x65, 0x49, 0x54, 0x2f, 0x41, 0x50, 0x49, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x32, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_common_common_proto_rawDescOnce sync.Once
	file_pkg_grpc_common_common_proto_rawDescData = file_pkg_grpc_common_common_proto_rawDesc
)

func file_pkg_grpc_common_common_proto_rawDescGZIP() []byte {
	file_pkg_grpc_common_common_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_common_common_proto_rawDescData)
	})
	return file_pkg_grpc_common_common_proto_rawDescData
}

var file_pkg_grpc_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_grpc_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_common_common_proto_goTypes = []interface{}{
	(GrpPermissionLevel)(0), // 0: v1alpha2.common.GrpPermissionLevel
	(SharingStatus)(0),      // 1: v1alpha2.common.SharingStatus
	(*StatusReport)(nil),    // 2: v1alpha2.common.StatusReport
	(*Empty)(nil),           // 3: v1alpha2.common.Empty
}
var file_pkg_grpc_common_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_common_common_proto_init() }
func file_pkg_grpc_common_common_proto_init() {
	if File_pkg_grpc_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_common_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_common_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_common_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_grpc_common_common_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_common_common_proto_depIdxs,
		EnumInfos:         file_pkg_grpc_common_common_proto_enumTypes,
		MessageInfos:      file_pkg_grpc_common_common_proto_msgTypes,
	}.Build()
	File_pkg_grpc_common_common_proto = out.File
	file_pkg_grpc_common_common_proto_rawDesc = nil
	file_pkg_grpc_common_common_proto_goTypes = nil
	file_pkg_grpc_common_common_proto_depIdxs = nil
}
